### ISSUE TITLE
No music without another vessel/debris

### ISSUE THREAD

**Issue by schpoorky** [pizzaoverhead/SoundtrackEditor#5]
When `scene = FLIGHT`, regardless of `playWhen` conditions being met, no playlist will be selected unless another vessel exists, whether that vessel is loaded or unloaded.

**Comment by schpoorky** [comment]
Suspect that handling of 'NearestVessel' is acting as unintended block to processing other prerequisites. Currently this feature isn't accessible or usable. Suggest commenting out or removing to a feature branch until it is fully working.

**Comment by schpoorky** [comment]
Fixed by commenting out NearestVessel code. 
Pull request -- https://github.com/pizzaoverhead/SoundtrackEditor/pull/13

**Comment by pizzaoverhead** [comment]
Fixed in 1.4.5.
